### ISSUE TITLE
General Review

### ISSUE THREAD

**Issue by lander2k2** [rleekin/kubectl-basics#1]
Looks great overall.  Just a few points to add a little polish...

- [x] You have used "Kubectl" with a capital "K" throughout.  I suggest using "kubectl" with lower case "k" everywhere, even in titles.  That will align with the [kubernetes docs](https://kubernetes.io/docs/tasks/tools/install-kubectl/) and improve consistency.
- [x] Step 1 instructions include "So let’s look at the the Kubernetes cluster information.  Let’s look at the Kubernetes version running the cluster."  Using "Let's look at" in consecutive sentences feels repetitive.  Suggest slightly different wording.
- [x] Step 1: "You’ll see the not just the Kubernetes version" - Sentence construction typo?
- [x] Use consistent casing for Kubernetes resources.  For example Step 3 includes "node" and "Nodes".  FWIW the Kubernetes docs seem to use [uppercase](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#composing)
- [x] Step 6: "Look at the pods in the Kube-System Namespace."  Suggest lower case for namespace names.  This also applies to several other steps.
- [x] Step 8: "Check to see if the deployment is in the "Ready" stage."  Is a little more correct to say it is in a "Ready" *condition*
- [x] Step 12: "If you want to sort the information output, this command is helpful"  Suggest using "flag" instead of "command".  Technically you're using the same command with the `--sort-by` flag.
- [x] Step 13: "help you be more efficient at Kubectl" Suggest slightly different wording: "help you be more efficient *using* kubectl".

**Comment by rleekin** [comment]
Thanks for the feedback. I have made the suggested changes.
